### ISSUE TITLE
Fails eslint test

### ISSUE THREAD

**Issue by molson504x** [uken/react-countdown-timer#7]
This will fail most eslint passes (countdown_timer.jsx):

```
  17:40  error  Unexpected trailing comma  comma-dangle
  92:23  error  Missing radix parameter    radix
  93:23  error  Missing radix parameter    radix
  94:21  error  Missing radix parameter    radix
```

The comma dangle rule I normally suppress in a project, as do most people I assume.  but the radix rule one should be corrected.  You should probably specify the radix in the parseInt calls just to be safe (what if totalSeconds % 60 comes out to 0?  It'll default to an octal number).

**Comment by rvierich** [comment]
Fixed in this commit: https://github.com/uken/react-countdown-timer/commit/e5f33fd47a0eec9b12645f76b549ded743df5f59
